- schema.graphql
- src/RealitioMapping.ts
- subgraph.template.yaml
- test/omen-subgraph.js
> Parse question

- schema.graphql
- src/ConditionalTokensMapping.template.ts
- src/RealitioMapping.template.ts
Resolves #9 
This also adds a field `numOpenConditions`. Using conditions as a proxy for open markets because tracking a market's lifecycle on the graph is a bit tricky.
> Add category entity

- contracts/Deps.sol
- render-templates.js
- schema.graphql
- src/FPMMDeterministicFactoryMapping.template.ts
- src/FixedProductMarketMakerMapping.ts
- src/day-volume-utils.ts
- src/fpmm-utils.ts
- subgraph.template.yaml
Should close #13 
Adds scaled versions of some fields.
> Scale volume metrics using ERC-20 decimals query

- schema.graphql
- src/FixedProductMarketMakerMapping.ts
- test/omen-subgraph.js
> Record participants of markets using join table

- schema.graphql
- src/FPMMDeterministicFactoryMapping.template.ts
- src/FixedProductMarketMakerMapping.ts
- src/fpmm-utils.ts
> Add scaledLiquidityParameter field

- schema.graphql
- src/ConditionalTokensMapping.template.ts
- src/RealitioMapping.template.ts
- src/global-utils.ts
Should resolve #11 
I added a singleton Global entity as well, since putting it as a Category entity opens the global entity up to an ID collision attack.
> More condition counts

- schema.graphql
- src/FixedProductMarketMakerMapping.ts
> Lift fields from FPMM to FPMMParticipation

- schema.graphql
- src/DXTokenRegistryMapping.ts
- src/FPMMDeterministicFactoryMapping.template.ts
- src/FixedProductMarketMakerMapping.ts
- subgraph.template.yaml
Should resolve #33 
Deployed to the [gnosis/omen](https://thegraph.com/explorer/subgraph/gnosis/omen) subgraph.
@cbrzn this PR clobbers your original specs... hope this is okay.
> Curate fpmms

- schema.graphql
- src/FPMMDeterministicFactoryMapping.template.ts
- src/FixedProductMarketMakerMapping.ts
- src/fpmm-utils.ts
- test/omen-subgraph.js
> Add liquidity measure

- schema.graphql
- src/ConditionalTokensMapping.template.ts
- src/FPMMDeterministicFactoryMapping.template.ts
- src/FixedProductMarketMakerMapping.ts
- src/constants.ts
- src/day-volume-utils.ts
- src/fpmm-utils.ts
- src/nth-root.ts
> Hourly daily volume

- src/FixedProductMarketMakerMapping.ts
- test/omen-subgraph.js
Closes: https://github.com/protofire/omen-subgraph/issues/37
This change doesn't work if I deploy to my own forked subgraph, but as far as I can tell it should work fine, so I'm not sure if I've done something incorrectly or if I'm misunderstanding something.
> Record participation of liquidity provision

- schema.graphql
- src/FixedProductMarketMakerMapping.ts
Closes https://github.com/protofire/omen-subgraph/issues/55
> Add title to fpmmParticipation

- schema.graphql
- src/FPMMDeterministicFactoryMapping.template.ts
- src/GeneralizedTCRMapping.ts
- test/omen-subgraph.js
Reverts protofire/omen-subgraph#57
> Revert "fix: incorrect `klerosTCRregistered` for markets with multiple submissions."

- schema.graphql
- src/FPMMDeterministicFactoryMapping.template.ts
- src/GeneralizedTCRMapping.ts
- test/omen-subgraph.js
Reverts protofire/omen-subgraph#59
> Revert "Revert "fix: incorrect `klerosTCRregistered` for markets with multiple submissions.""

- package.json
- schema.graphql
- src/FixedProductMarketMakerMapping.ts
Add tradeNonce to Account entiy:
* Increment the `tradeNonce` on every sell or buy event.
* Fix FPMMTrade duplicated ids.
> Add trade nonce

- package.json
- src/FixedProductMarketMakerMapping.ts
The `tradeNonce` BigInt was not being updated after record a new trade entity.
> Fix set `account.tradeNonce` on recordTrade

- networks.json
This should help with the codeship failures.
> Deploy RealitioScalarAdapter on Rinkeby and Mainnet

- schema.graphql
- src/ConditionalTokensMapping.template.ts
- src/FPMMDeterministicFactoryMapping.template.ts
- src/RealitioMapping.template.ts
- test/omen-subgraph.js
This makes the scalar information more readily available.
> Copy bounds to condition and FPMM entities

- package.json
- schema.graphql
- src/FixedProductMarketMakerMapping.ts
Add field `collateralAmountUSD` as BigDecimal in **FPMMTrade** entity to calculate the value of `collateralAmount` in USD value at the moment of the trade.
Resolves: #72
>  Add amount from collateral Trade in USD

- networks.json
Should be merged with https://github.com/protofire/omen-exchange/pull/1206
Related: https://github.com/protofire/omen-exchange/issues/1207
> Use original ConditionalTokens deployed on Rinkeby

- schema.graphql
- src/DXTokenRegistryMapping.ts
- subgraph.template.yaml
Working Example:
https://thegraph.com/explorer/subgraph/astro514/omen?selected=playground
> Move DXTokenRegistry tokenList to subgraph

- networks.json
> Use redeployed oracles with corrected CT on Rinkeby

- networks.json
Update Realty contract addresses for Sokol and xDai
See https://github.com/protofire/omen-exchange/pull/1543/
> Update Reality contracts for Sokol and xDai

- networks.json
Closes: https://github.com/protofire/omen-subgraph/issues/128
Closes: https://github.com/protofire/omen-subgraph/issues/127
> Update arbitration contracts on mainnet, xdai, sokol

- schema.graphql
- src/RealitioMapping.template.ts
This adds a couple minor improvements to Realitio indexing:
* saves the timestamp of submitted answers
* store arbitration request details
* update the current answer when arbitration finalises
> Index arbitration info from Realitio

- schema.graphql
- src/FPMMDeterministicFactoryMapping.template.ts
- test/omen-subgraph.js
closes https://github.com/protofire/omen-subgraph/issues/181
Had a go @KadenZipfel 😄 does this look right?
> Add oracle field to FixedProductMarketMaker
